services:
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

  postgres:
    image: postgres:16
    container_name: postgres_dapp
    restart: always

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/senha123
    ports:
      - "7474:7474" # Interface web
      - "7687:7687" # Bolt (conexão)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
  redis_data:
  postgres_data:
